game: survivors
dry_run: false
host: 127.0.0.1
port: null
n_envs: 4
vec_env_type: subproc
n_steps: 1024
base_port: 8768
eval_port: 8767
total_steps: 8000000
version_name: v08
run_name: 01_main
checkpoint_freq: 100000
entity_attention: true
dist_alpha: 1.0
reward_fn: runs/survivors/v08/reward_fn/reward_fn.py
no_vec_normalize: false
anneal_threshold: 0.05
anneal_steps: 1000000
anneal_check_freq: 20000
anneal_min_steps: 1000000
anneal_min_weight: 0.1
noveld: true
noveld_beta: 0.3
noveld_alpha: 0.5
ent_coef: 0.05
n_epochs: 5
clip_range: 0.2
learning_rate: 0.0003
batch_size: 256
target_kl: 0.02
device: cuda
frame_skip: 4
frame_stack: 1
recurrent: true
lstm_hidden_size: 256
n_lstm_layers: 1
curriculum: false
curriculum_window: 20
curriculum_threshold: 1.0
curriculum_alive_reward: 0.001
until_curriculum_complete: false
curriculum_complete_window: 20
curriculum_complete_min_episodes: 20
curriculum_complete_min_score_ratio: 1.0
curriculum_complete_min_episode_len_ratio: 1.0
spalf: false
spalf_r_b: 0.4
spalf_alpha: 0.2
spalf_buffer_size: 200
spalf_warmup_episodes: 50
spalf_max_score: 15000
curriculum_spalf: true
eval_freq: 50000
eval_episodes: 5
init_model: null
init_vecnormalize: null
weapon_phase: auto
weapon_phase_auto_stagnation_steps: 500000
wandb: true
wandb_project: survivors-v08
wandb_run_name: 01-main
