"""証跡JSONとSteamビルドマニフェストから実測値を集め、.env/target_profile.resolved.yaml を生成するCLI。

tracked のテンプレート(mad_forest_standard_v1.yaml)は一切書き換えません。実行ファイルの
バージョン・Steamのビルド番号・OS/GPU実測値・torchバージョン・saveファイルのVersionフィールドを
機械的に読み取り、git管理外の .env/ へ「確定版プロファイル」を1ファイル丸ごと書き出します。
書き出す前に target_audit.py の本物の検証関数で自己チェックし、1つでも落ちたら何も書きません。
"""

from __future__ import annotations

import argparse
import copy
import getpass
import json
import re
import sys
from dataclasses import dataclass
from datetime import date
from pathlib import Path
from typing import Any, Mapping

import yaml

from reinbalance_survivors_contracts.canonical_json import canonical_hash
from .target_audit import (
    _ATTESTED_PROFILE_FIELDS,
    AuditError,
    _assert_canonical_identity_finalized,
    _assert_resolved,
    _valid_manual,
)
from .target_profile import CONFIG, RESOLVED, TargetProfile, load_target_profile

# .env/survivors_deployment.env のパス。許可キーのホワイトリストは PowerShell 側
# (SurvivorsDeployment.Common.ps1) が持っているため、ここでは検査しない。
ENV_FILE = Path(__file__).parents[3] / ".env" / "survivors_deployment.env"
_STEAM_APP_ID = "1794680"
_BUILDID_RE = re.compile(r'"buildid"\s+"(\d+)"')
_HEADER = (
    b"# auto-generated by target_resolve.py - do not edit by hand.\n"
    b"# from Tools/Deployment: python -m survivors.target_resolve\n"
    b"\xe3\x81\x97\xe3\x81\xa6\xe3\x81\x8f\xe3\x81\xa0\xe3\x81\x95\xe3\x81\x84\xe3\x80\x82\n"
)


@dataclass(frozen=True)
class Measurements:
    """resolved profile を組み立てるのに必要な実測値ちょうど一式。

    証跡ファイルの読み取り結果をここへ一度詰め替えることで、「どの値がどこから来たか」を
    ファイルI/Oと切り離してテストできるようにします。
    """

    build_id: str
    executable_version: str
    executable_hash: str
    save_artifact_hash: str
    save_format_version: int
    os_build: str
    gpu_name: str
    vram_mb: int
    driver_version: str
    cuda_version: str
    pytorch_version: str
    operator: str
    date: str


def parse_env_file(text: str) -> dict[str, str]:
    """`.env/survivors_deployment.env` の `KEY="value"` 形式を辞書へ変換する。

    コメント行(`#`)と空行は無視します。値の前後を囲む一重/二重引用符は剥がします。
    python-dotenv 等の外部ライブラリは使わず、この最小限のパーサだけで済ませます。
    """
    result: dict[str, str] = {}
    for line in text.splitlines():
        stripped = line.strip()
        if not stripped or stripped.startswith("#"):
            continue
        key, sep, value = stripped.partition("=")
        if not sep:
            continue
        key = key.strip()
        value = value.strip()
        if len(value) >= 2 and value[0] == value[-1] and value[0] in "\"'":
            value = value[1:-1]
        result[key] = value
    return result


def parse_steam_build_id(acf_text: str) -> str:
    """Steam の appmanifest(.acf) テキストから `buildid` を文字列で抽出する。

    この関数を通った時点で必ず `str` を返す。PyYAML の型推論で int 化され
    `window_locator.py` の `isinstance(build_id, str)` 検査に落ちる事故を防ぐため。
    """
    m = _BUILDID_RE.search(acf_text)
    if not m:
        raise ValueError("buildid not found in appmanifest")
    return m.group(1)


def find_steam_appmanifest(executable: Path, app_id: str = _STEAM_APP_ID, max_levels: int = 6) -> Path:
    """実行ファイルのパスから親ディレクトリを遡り、Steamのappmanifestを探す。"""
    name = f"appmanifest_{app_id}.acf"
    current = executable.parent
    for _ in range(max_levels):
        for candidate in (current / "steamapps" / name, current / name):
            if candidate.is_file():
                return candidate
        if current.parent == current:
            break
        current = current.parent
    raise FileNotFoundError(f"{name} was not found within {max_levels} parent levels of {executable}")


def _read_json_bom(path: Path) -> Any:
    """BOM付きUTF-8で書かれた証跡JSONを読む(encoding="utf-8-sig")。

    BOMが無いファイル(SaveDataなど)でも問題なく読める。
    """
    with path.open(encoding="utf-8-sig") as f:
        return json.load(f)


def latest_evidence_manifest(evidence_root: Path) -> Path:
    """`target-evidence-*.json` のうち名前降順(=最新の収集時刻)のものを返す。"""
    candidates = sorted(evidence_root.glob("target-evidence-*.json"), reverse=True)
    if not candidates:
        raise FileNotFoundError(f"no target-evidence-*.json found under {evidence_root}")
    return candidates[0]


def build_measurements(
    manifest: Mapping[str, Any],
    machine_info: Mapping[str, Any],
    executable_metadata: Mapping[str, Any],
    *,
    build_id: str,
    save_format_version: int,
    pytorch_version: str,
    cuda_version: str,
    operator: str,
    date_str: str,
) -> Measurements:
    """パース済みの証跡JSON3種から Measurements を組み立てる(純粋関数・実機不要)。

    過去に実行ファイルのハッシュを save_artifact_hash に取り違えた不具合があったため、
    「どの証跡フィールドがどの出力フィールドになるか」をここ1箇所に閉じ込めてテストで固定する。
    """
    gpu = machine_info["gpu"][0]
    exe_meta = executable_metadata["executable"]
    executable_version = exe_meta.get("file_version") or exe_meta.get("product_version") or ""
    return Measurements(
        build_id=str(build_id),
        executable_version=executable_version,
        executable_hash=manifest["executable"]["canonical_hash"],
        save_artifact_hash=manifest["canonical_save"]["canonical_hash"],
        save_format_version=int(save_format_version),
        os_build=str(machine_info["os"]["BuildNumber"]),
        gpu_name=gpu["Name"],
        vram_mb=int(round(float(gpu["VRAM_GiB"]) * 1024)),
        driver_version=gpu["DriverVersion"],
        cuda_version=cuda_version,
        pytorch_version=pytorch_version,
        operator=operator,
        date=date_str,
    )


def manual_evidence_doc(m: Measurements) -> dict:
    """`target_audit.audit_target()` が要求する measurements 文書を作る。

    `target_audit.py` の `claimed` 辞書と1文字も違わないキー・値になっていないと監査が落ちる。
    """
    return {
        "schema_version": "survivors_manual_attestation.v1",
        "measurements": {
            "build_id": m.build_id,
            "executable_version": m.executable_version,
            "save_format_version": m.save_format_version,
            "os_build": m.os_build,
            "gpu_name": m.gpu_name,
            "vram_mb": m.vram_mb,
            "driver_version": m.driver_version,
            "cuda_version": m.cuda_version,
            "pytorch_version": m.pytorch_version,
        },
    }


def manual_evidence_bytes(m: Measurements) -> bytes:
    """`manual_evidence_doc` を、ハッシュ対象になる確定バイト列へ直列化する。

    改行がCRLFに化けるとバイト列が変わりハッシュが監査と一致しなくなるため、
    明示的にLFへ固定してからエンコードする。
    """
    text = yaml.safe_dump(manual_evidence_doc(m), sort_keys=True, allow_unicode=True)
    return text.replace("\r\n", "\n").encode("utf-8")


def build_resolved_wire(template_wire: Mapping[str, Any], m: Measurements, evidence_hash: str) -> dict:
    """テンプレートのwireに実測値を流し込み、provenanceをoperator-attestedへ倒したwireを返す。

    入力のテンプレートはdeepcopyし変更しない。埋めるのはbuild/progression/hardwareの
    実測フィールドとmanual_attestationの5キーだけで、それ以外の正準値はテンプレートのまま残す。
    """
    wire = copy.deepcopy(dict(template_wire))
    wire["provenance"] = "operator-attested"
    wire["build"] = {
        **wire["build"],
        "build_id": m.build_id,
        "executable_version": m.executable_version,
        "executable_hash": m.executable_hash,
        "manual_attestation": {
            "operator": m.operator,
            "date": m.date,
            "evidence_hash": evidence_hash,
            "fields": sorted(field for _, field in _ATTESTED_PROFILE_FIELDS),
            "unavailable_reason": (
                "メモリ読み取り・DLLインジェクションを行わない方針のため、これらの値はゲーム内部状態から"
                "自動取得できない。実行ファイルのバージョン情報・Steamビルドマニフェスト・OS/GPU実測値・"
                "torchバージョン・saveファイルのVersionフィールドを機械的に読み取って記録した。"
            ),
        },
    }
    wire["progression"] = {
        **wire["progression"],
        "save_artifact_hash": m.save_artifact_hash,
        "save_format_version": m.save_format_version,
    }
    wire["hardware"] = {
        **wire["hardware"],
        "os_build": m.os_build,
        "gpu_name": m.gpu_name,
        "vram_mb": m.vram_mb,
        "driver_version": m.driver_version,
        "cuda_version": m.cuda_version,
        "pytorch_version": m.pytorch_version,
    }
    return wire


def validate_resolved_wire(wire: Mapping[str, Any]) -> None:
    """書き出す前に、本番の監査コードそのもので resolved wire を自己検証する。

    スキーマ検査・プレースホルダ残存検査・manual_attestationの形・canonical identity確定の
    4つを通す。1つでも落ちれば例外を投げ、呼び出し側は何も書かない(fail-closed)。
    """
    TargetProfile.from_wire(wire)
    _assert_resolved(wire)
    if not _valid_manual(wire["build"]["manual_attestation"]):
        raise AuditError("manual_attestation shape invalid")
    _assert_canonical_identity_finalized(wire)


def collect_measurements(env: Mapping[str, str]) -> Measurements:
    """.envの3パスから実ファイルを読み、build_measurementsに渡してMeasurementsを得る。

    このモジュールで唯一「実機に触れる」関数。torchはここで遅延importし、
    他の純粋関数のテストをtorchのロード時間・有無で汚さないようにする。
    """
    import torch  # 遅延import: pytest収集時にtorchロードを強制しない

    evidence_root = Path(env["SURVIVORS_EVIDENCE_ROOT"])
    manifest_path = latest_evidence_manifest(evidence_root)
    manifest = _read_json_bom(manifest_path)
    machine_info = _read_json_bom(evidence_root / manifest["machine_info"]["basename"])
    executable_metadata = _read_json_bom(evidence_root / manifest["executable_metadata"]["basename"])

    executable = Path(env["VAMPIRE_SURVIVORS_EXE"])
    acf_path = find_steam_appmanifest(executable)
    build_id = parse_steam_build_id(acf_path.read_text(encoding="utf-8"))

    save_data = _read_json_bom(Path(env["SURVIVORS_CANONICAL_SAVE"]))

    return build_measurements(
        manifest,
        machine_info,
        executable_metadata,
        build_id=build_id,
        save_format_version=save_data["Version"],
        # torch.__version__ は str のサブクラス(TorchVersion)を返すため、明示的に str() へ落とす。
        # そのままだと yaml.safe_dump が型を認識できず RepresenterError になる。
        pytorch_version=str(torch.__version__),
        cuda_version=str(torch.version.cuda) if torch.version.cuda else "",
        operator=getpass.getuser(),
        date_str=date.today().isoformat(),
    )


def main(argv: list[str] | None = None) -> int:
    """.envを読み→実測→wire生成→自己検証→検証通過後にだけ2ファイルを書く。

    ユーザーが Tools/Deployment から python -m survivors.target_resolve を実行して使うCLI。
    途中で1つでも失敗したら何も書かずに非ゼロ終了する(fail-closed)。
    """
    parser = argparse.ArgumentParser(description="実機の実測値からresolved target profileを生成する")
    parser.add_argument("--env", type=Path, default=ENV_FILE)
    parser.add_argument("--template", type=Path, default=CONFIG)
    parser.add_argument("--output", type=Path, default=RESOLVED)
    args = parser.parse_args(argv)

    try:
        env = parse_env_file(args.env.read_text(encoding="utf-8"))
        measurements = collect_measurements(env)
        evidence_root = Path(env["SURVIVORS_EVIDENCE_ROOT"])
        body = manual_evidence_bytes(measurements)
        evidence_hash = canonical_hash({"bytes_hex": body.hex()})
        template_wire = load_target_profile(args.template).to_wire()
        wire = build_resolved_wire(template_wire, measurements, evidence_hash)
        validate_resolved_wire(wire)
    except Exception as exc:  # fail-closed: 検証を通るまで一切書き込まない
        print(f"resolve failed: {exc}", file=sys.stderr)
        return 1

    (evidence_root / "manual_attestation_evidence.yaml").write_bytes(body)
    payload = yaml.safe_dump(wire, sort_keys=True, allow_unicode=True).encode("utf-8")
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_bytes(_HEADER + payload)
    print(f"wrote {args.output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
