/**
 * Survivors Logic の one-way content/action schema を検証する LLT。
 * Windows の Low Level Tests で schema が enum/table/config 由来の主要項目を含むことを確認する。
 */
#include "TestHarness.h"

#include "Survivors/SurvivorsGameLogic.h"

TEST_CASE("Survivors content schema is generated by game logic", "[unit][survivors][logic][fidelity]")
{
	FSurvivorsGameLogic Logic;
	FSurvivorsGameLogicConfig Config;
	Logic.Initialize(Config);

	const FString Content = Logic.GetContentSchema();
	const FString ActionTime = Logic.GetActionTimeSchema();
	CHECK(Content.Contains(TEXT("\"xp_curve\"")));
	CHECK(Content.Contains(TEXT("\"evolutions\"")));
	CHECK(Content.Contains(TEXT("\"chest\"")));
	CHECK(ActionTime.Contains(TEXT("\"directions\"")));
	CHECK(ActionTime.Contains(TEXT("\"id\":8")));
	CHECK(ActionTime.Contains(TEXT("\"physics_dt\"")));
}
