"""Semantic validation for Survivors reward_fn.py generated by EUREKA."""

from __future__ import annotations

import re
from typing import Any


def _finding(severity: str, code: str, message: str, pattern: str) -> dict[str, str]:
    return {
        "severity": severity,
        "code": code,
        "message": message,
        "pattern": pattern,
    }


def _matches(code: str, pattern: str) -> bool:
    return re.search(pattern, code, flags=re.MULTILINE) is not None


def validate_survivors_reward_code(code: str, source_of_truth: dict[str, Any] | None) -> list[dict]:
    """Detect reward code that conflicts with C++ Survivors constants.

    The validator intentionally focuses on high-signal errors that previously
    slipped through the LLM review flow. It does not try to prove reward quality.
    """
    if not source_of_truth:
        return []

    reward = source_of_truth.get("reward_constants", {})
    player = source_of_truth.get("player_constants", {})
    item_reward = reward.get("ItemReward")
    kill_reward = reward.get("KillReward")
    max_player_hp = player.get("MaxPlayerHP")

    findings: list[dict] = []

    if item_reward == 1.0:
        item_error_patterns = [
            r"base_reward\s*(?:>=|>|==)\s*2\.9\b",
            r"base_reward\s*(?:>=|>|==)\s*3\.0\b",
            r"\bremaining\s*/\s*3\.0\b",
            r"\bItemReward\s*\(?\s*3\.0\b",
            r"\bITEM_REWARD\s*=\s*3\.0\b",
            r"\b_ITEM_REWARD\s*=\s*3\.0\b",
        ]
        for pattern in item_error_patterns:
            if _matches(code, pattern):
                findings.append(
                    _finding(
                        "error",
                        "ITEM_REWARD_MISMATCH",
                        "ItemReward is 1.0 in C++, but reward_fn appears to assume 3.0.",
                        pattern,
                    )
                )

    if kill_reward == 2.0:
        kill_warning_patterns = [
            r"\bKillReward\s*\(?\s*3\.0\b",
            r"\bKILL_REWARD\s*=\s*3\.0\b",
            r"\b_KILL_REWARD\s*=\s*3\.0\b",
            r"\bn_kills\s*=\s*int\s*\(\s*remaining\s*/\s*3\.0\s*\)",
        ]
        for pattern in kill_warning_patterns:
            if _matches(code, pattern):
                findings.append(
                    _finding(
                        "warning",
                        "KILL_REWARD_SUSPICIOUS",
                        "KillReward is 2.0 in C++; this code may be using a stale 3.0 scale.",
                        pattern,
                    )
                )

    if max_player_hp == 70.0:
        hp_patterns = [
            r"obs\s*\[\s*12\s*\]\s*\*\s*100\.0\b",
            r"\bMAX_PLAYER_HP\s*=\s*100\.0\b",
            r"\b_MAX_PLAYER_HP\s*=\s*100\.0\b",
        ]
        for pattern in hp_patterns:
            if _matches(code, pattern):
                findings.append(
                    _finding(
                        "error",
                        "MAX_HP_MISMATCH",
                        "MaxPlayerHP is 70.0 in C++, but reward_fn appears to use 100.0.",
                        pattern,
                    )
                )

    return findings
